name: CowCannon
version: '${project.version}'
main: org.mineacademy.cowcannon.CowCannon
api-version: '1.13'
commands:
  cow:
    description: "Spawn an exploding cow"
    usage: "/cow [set/baby] [entityType]"
    aliases: [ cowcannon ]
    permission: cowcannon.command.cow
    permission-message: "You do not have permission to spawn an exploding cow"
  butterfly:
    description: "Toggle particle effect"
    usage: "/butterfly"
    permission: cowcannon.command.butterfly
  displayentity:
    aliases: [ de ]
    description: "Spawns a display entity"
    usage: "/displayentity"
    permission: cowcannon.command.displayentity
  customitem:
    description: "Gives you a custom item"
    usage: "/customitem"
    permission: cowcannon.command.customitem
  gui:
    description: "Opens a GUI"
    usage: "/gui"
    permission: cowcannon.command.gui
permissions:
  cowcannon.command.cow:
    default: op
  cowcannon.cow.use:
    default: true