name: CowCannon
version: '${project.version}'
main: org.mineacademy.cowcannon.CowCannon
api-version: '1.13'
softdepend: [ Vault, ProtocolLib, PlaceholderAPI, DiscordSRV ]
libraries:
  - org.jsoup:jsoup:1.16.1

commands:
  cow:
    description: "Spawn an exploding cow"
    usage: "/cow [set/baby] [entityType]"
    aliases: [ cowcannon ]
    permission: cowcannon.command.cow
    permission-message: "You do not have permission to spawn an exploding cow"
  butterfly:
    description: "Toggle particle effect"
    usage: "/butterfly"
    permission: cowcannon.command.butterfly
  displayentity:
    aliases: [ de ]
    description: "Spawns a display entity"
    usage: "/displayentity"
    permission: cowcannon.command.displayentity
  customitem:
    description: "Gives you a custom item"
    usage: "/customitem"
    permission: cowcannon.command.customitem
  gui:
    description: "Opens a GUI"
    usage: "/gui"
    permission: cowcannon.command.gui
  read:
    description: "Reads a webpage from the Internet."
    usage: "/read <url>"
    permission: cowcannon.command.read
  economy:
    description: "Manages Cow economy."
    usage: "/economy <view/take/give> <player> [amount]"
    aliases: [ eco, money, balance, bal ]
    permission: cowcannon.command.economy
  giant:
    description: "Spawns a Giant Boss."
    usage: "/giant"
    permission: cowcannon.command.giant
  psycho:
    description: "Spawns a Psycho custom NMS mob."
    usage: "/psycho"
    permission: cowcannon.command.psycho
permissions:
  cowcannon.command.cow:
    default: op
  cowcannon.cow.use:
    default: true