name: CowCannon
version: '${project.version}'
main: org.mineacademy.cowcannon.CowCannon
api-version: '1.13'
commands:
  cow:
    description: "Spawn an exploding cow"
    usage: "/cow [set/baby] [entityType]"
    aliases: [ cowcannon ]
    permission: cowcannon.command.cow
    permission-message: "You do not have permission to spawn an exploding cow"
  butterfly:
    description: "Toggle particle effect"
    usage: "/butterfly"
    permission: cowcannon.command.butterfly
permissions:
  cowcannon.command.cow:
    default: op
  cowcannon.cow.use:
    default: true