name: CowCannon
version: '${project.version}'
main: org.mineacademy.cowcannon.CowCannon
api-version: '1.13'
softdepend: [ Vault, ProtocolLib, PlaceholderAPI ]
folia-supported: true
libraries:
  - org.jsoup:jsoup:1.18.3
  - com.theokanning.openai-gpt3-java:service:0.18.2
  - com.sendgrid:sendgrid-java:4.10.3
  - org.openjdk.nashorn:nashorn-core:15.6
commands:
  tag:
    description: "Change a player tag above his head."
    usage: "/tag <newTag/reset>"
    permission: cowcannon.command.tag
permissions:
  cowcannon.command.cow:
    default: op
  cowcannon.cow.use:
    default: true